# Generated by Django 3.2.12 on 2022-03-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('success_story', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'users_profile',
            },
        ),
    ]
