# Generated by Django 3.2.12 on 2022-03-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user_profile'},
        ),
    ]
