# Generated by Django 3.2.12 on 2022-03-29 16:47

import Apply.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('hs', 'highschool'), ('ud', 'undergraduate'), ('gd', 'graduate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='', validators=[Apply.validators.validate_file_extension]),
        ),
    ]
