# Generated by Django 3.2.12 on 2022-03-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0003_auto_20220329_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profile'},
        ),
    ]
