# Generated by Django 3.2.12 on 2022-03-29 17:52

import Apply.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('hs', 'Highschool'), ('ud', 'Undergraduate'), ('gd', 'Graduate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', validators=[Apply.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='Apply.Interests'),
        ),
    ]
