# Generated by Django 3.2.12 on 2022-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0005_auto_20220329_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
