# Generated by Django 3.2.12 on 2022-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0007_auto_20220405_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('hs', 'Highschool'), ('ud', 'Undergraduate'), ('gd', 'Graduate')], max_length=2),
        ),
    ]
