# Generated by Django 3.2.12 on 2022-04-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0008_alter_profile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('hs', 'Highschool'), ('ud', 'Undergraduate'), ('gd', 'Graduate')], default='ud', max_length=2),
        ),
    ]
