# Generated by Django 3.2.12 on 2022-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0009_alter_profile_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField()),
            ],
        ),
    ]
