# Generated by Django 3.2.12 on 2022-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0010_user_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_interests',
            options={'verbose_name': 'user interests'},
        ),
        migrations.RemoveField(
            model_name='user_interests',
            name='test',
        ),
        migrations.AddField(
            model_name='user_interests',
            name='art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_interests',
            name='athletics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_interests',
            name='bio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_interests',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_interests',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_interests',
            name='tech',
            field=models.BooleanField(default=False),
        ),
    ]
