# Generated by Django 3.2.12 on 2022-04-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0011_auto_20220405_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apply.user_interests'),
        ),
    ]
