# Generated by Django 3.2.12 on 2022-04-05 17:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0013_alter_profile_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tech', 'Technology'), ('med', 'Medical'), ('art', 'Art'), ('ath', 'Athletics'), ('fin', 'Finance'), ('bus', 'Business')], max_length=5),
        ),
    ]
