# Generated by Django 3.2.12 on 2022-04-07 15:57

import Apply.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apply', '0014_auto_20220405_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100000)),
                ('expected_salary', models.IntegerField()),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('resume', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', validators=[Apply.validators.validate_file_extension])),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_Interests',
        ),
    ]
