# Generated by Django 3.2.12 on 2022-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0015_auto_20220407_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(max_length=10000000),
        ),
    ]
