# Generated by Django 3.2.12 on 2022-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0022_alter_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
