# Generated by Django 3.2.12 on 2022-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0024_alter_jobs_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
