# Generated by Django 3.2.12 on 2022-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0027_alter_profile_success_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
