# Generated by Django 3.2.12 on 2022-05-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0028_auto_20220424_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apply.jobs'),
        ),
    ]
