# Generated by Django 3.2.12 on 2022-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0029_profile_saved_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_jobs',
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, null=True, to='Apply.Jobs'),
        ),
    ]
