# Generated by Django 3.2.12 on 2022-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0030_auto_20220501_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='Apply.Jobs'),
        ),
    ]
