# Generated by Django 3.2.12 on 2022-05-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0031_alter_profile_saved_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
    ]
