# Generated by Django 3.2.12 on 2022-05-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0032_remove_jobs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
