# Generated by Django 3.2.12 on 2022-05-09 02:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0034_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bos', 'Boston, MA'), ('ny', 'New York, NY'), ('chic', 'Chicago, IL'), ('phil', 'Philadelphia, PA'), ('hous', 'Houston, TX'), ('phnx', 'Phoenix, AZ'), ('la', 'Los Angeles, CA')], max_length=29),
        ),
        migrations.AddField(
            model_name='profile',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bos', 'Boston, MA'), ('ny', 'New York, NY'), ('chic', 'Chicago, IL'), ('phil', 'Philadelphia, PA'), ('hous', 'Houston, TX'), ('phnx', 'Phoenix, AZ'), ('la', 'Los Angeles, CA')], max_length=29),
        ),
    ]
