# Generated by Django 3.2.12 on 2022-05-09 19:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0035_auto_20220508_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bos', 'Boston, MA'), ('ny', 'New York, NY'), ('chic', 'Chicago, IL'), ('phil', 'Philadelphia, PA'), ('hous', 'Houston, TX'), ('phnx', 'Phoenix, AZ'), ('sea', 'Seattle, WA'), ('mia', 'Miami, FL')], max_length=34),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bos', 'Boston, MA'), ('ny', 'New York, NY'), ('chic', 'Chicago, IL'), ('phil', 'Philadelphia, PA'), ('hous', 'Houston, TX'), ('phnx', 'Phoenix, AZ'), ('sea', 'Seattle, WA'), ('mia', 'Miami, FL')], max_length=34),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bos', 'Boston, MA'), ('ny', 'New York, NY'), ('chic', 'Chicago, IL'), ('phil', 'Philadelphia, PA'), ('hous', 'Houston, TX'), ('phnx', 'Phoenix, AZ'), ('sea', 'Seattle, WA'), ('mia', 'Miami, FL')], max_length=34),
        ),
    ]
