# Generated by Django 3.2.12 on 2022-05-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0036_auto_20220509_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='expected_tution',
            new_name='expected_tuition',
        ),
    ]
