# Generated by Django 3.2.12 on 2022-05-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0038_comment_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='success_story',
        ),
    ]
