# Generated by Django 3.2.12 on 2022-05-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0039_remove_profile_success_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_stories',
            field=models.ManyToManyField(blank=True, to='Apply.Story'),
        ),
    ]
