# Generated by Django 3.2.12 on 2022-05-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0039_remove_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
