# Generated by Django 3.2.12 on 2022-05-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0036_auto_20220510_0856'),
        ('Apply', '0041_story_interests'),
    ]

    operations = [
    ]
