# Generated by Django 3.2.12 on 2022-05-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0044_alter_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
    ]
